# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SC2ProfileMiner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SC2ProfileMiner
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'ObjectMapper'
  pod 'PKHUD'
  
  target 'SC2ProfileMinerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
